name: FiveM FXAP Scanner Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout completo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extrair versão
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar e enviar tag
        run: |
          git tag "${{ env.version }}"
          git push origin "${{ env.version }}"

      - name: Criar GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name:     ${{ env.version }}
          release_name: "FiveM FXAP Scanner v${{ env.version }}"
          draft:        false
          prerelease:   ${{ contains(env.version, 'alpha') || contains(env.version, 'beta') }}

  build-and-upload:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build App (gera pasta release/)
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: List artifacts
        run: ls -lh release/

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: release
          asset_name: |
            **/*
          asset_content_type: application/octet-stream
