name: FiveM FXAP Scanner Build

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout completo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extrair versão
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Criar e enviar tag
        run: |
          git tag "${{ env.version }}"
          git push origin "${{ env.version }}"

      - name: Criar GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          # sem token/repo_token aqui — a action usa GITHUB_TOKEN por padrão
          tag_name:     ${{ env.version }}
          release_name: "FiveM FXAP Scanner v${{ env.version }}"
          draft:        false
          prerelease:   ${{ contains(env.version, 'alpha') || contains(env.version, 'beta') }}

  build-and-upload:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build App (gera pasta release/)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          RAW_UPLOAD_URL: ${{ needs.create-release.outputs.upload_url }}
        run: |
          # Remove o sufixo "{?name,label}" do upload_url
          UPLOAD_URL="${RAW_UPLOAD_URL%\{*}"
          echo "Enviando assets para $UPLOAD_URL"
          for file in release/*; do
            name=$(basename "$file")
            echo "→ $name"
            curl --fail -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$file" \
              "$UPLOAD_URL?name=$name"
          done
